// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmmgUEcbKtry4TKgzYirRhTqR3PAQxSNA',
    appId: '1:819534543345:web:8f6bc13092b426b94f2c50',
    messagingSenderId: '819534543345',
    projectId: 'transpro-29ee3',
    authDomain: 'transpro-29ee3.firebaseapp.com',
    storageBucket: 'transpro-29ee3.firebasestorage.app',
    measurementId: 'G-MB9184LBMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB9w4HN-px5mcRjEX7FKpjrPhax7L2iW8',
    appId: '1:819534543345:android:83c71dde87dfc8b14f2c50',
    messagingSenderId: '819534543345',
    projectId: 'transpro-29ee3',
    storageBucket: 'transpro-29ee3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpyvnTVZxk4sm54ik5s8yhyg5c2UglRlM',
    appId: '1:819534543345:ios:b1e22373d25daa3c4f2c50',
    messagingSenderId: '819534543345',
    projectId: 'transpro-29ee3',
    storageBucket: 'transpro-29ee3.firebasestorage.app',
    iosBundleId: 'com.codebotx.transpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpyvnTVZxk4sm54ik5s8yhyg5c2UglRlM',
    appId: '1:819534543345:ios:b1e22373d25daa3c4f2c50',
    messagingSenderId: '819534543345',
    projectId: 'transpro-29ee3',
    storageBucket: 'transpro-29ee3.firebasestorage.app',
    iosBundleId: 'com.codebotx.transpro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmmgUEcbKtry4TKgzYirRhTqR3PAQxSNA',
    appId: '1:819534543345:web:b76a9364af5c32bc4f2c50',
    messagingSenderId: '819534543345',
    projectId: 'transpro-29ee3',
    authDomain: 'transpro-29ee3.firebaseapp.com',
    storageBucket: 'transpro-29ee3.firebasestorage.app',
    measurementId: 'G-5XKW00QDC1',
  );

}